mob
	Stat()
		ASSERT(src)
		statpanel("[src.name]")
		stat("Rating:","[Commas(round(rating,1))]")
		stat("Move Level:","[round(move_lvl,1)]")
	//	stat("Health:","[round(Health)]%")
	//	stat("Ki:","[round((Ki/MaxKi)*100)]%")
	//	if(primed && !inDecline) stat("<font color=#46EC46>Age:","<font color=#46EC46>[round(Age,0.1)] Physical Age")
		//else
		//	if(!primed && !inDecline)
		stat("Age:","[round(age,0.1)] Physical Age")
		//if(inDecline)
		//	stat("<font color=#E83030>Age:","<font color=#E83030>[round(age,0.1)] Physical Age")
		stat("Gravity:","[grav]([round(gravity_mastered)]x)")
	//	if(locatorOn) stat("Location:","([src.x]),([src.y])")
		stat("Quality Percentage:","[(round(intxp*10000,0.01))/round(10000,0.01)]%")
		if(race=="Oni"||race=="Namekian"||race=="Makyo"||race=="Demon"||race=="Wizard"||race=="Witch"||race=="Kai"||race=="Spirit Doll") stat("Magical Efficiency:","[(round(magicxp*10000))/10000]%")
	//	if(Ranked==1) stat("Occupation:","[Occupation]")
		///put total stats var for below average stuff
		stat("Strength","[(TextPercent(round(strength)))]")
		stat("Endurance","[(TextPercent(round(endurance)))]")
		stat("Force","[(TextPercent(round(force)))]")
		stat("Resistance","[(TextPercent(round(resistance)))]")
		if(mod_agility<=0.5)
			stat("Speed","Extremely Low")
		if(mod_agility>0.5&&mod_agility<=1.0)
			stat("Speed","Very Low")
		if(mod_agility>1.0&&mod_agility<=1.5)
			stat("Speed","Low")
		if(mod_agility>1.5&&mod_agility<=2.0)
			stat("Speed","Below Average")
		if(mod_agility>2.0&&mod_agility<=2.5)
			stat("Speed","Average")
		if(mod_agility>2.5&&mod_agility<=3.0)
			stat("Speed","Above Average")
		if(mod_agility>3.0&&mod_agility<=3.5)
			stat("Speed","High")
		if(mod_agility>3.5&&mod_agility<=4.0)
			stat("Speed","Very High")
		if(mod_agility>4.0)
			stat("Speed","Extremely High")
		stat("Offense","[(TextPercent(round(offence)))]")
		stat("Defense","[(TextPercent(round(defence)))]")
		stat("Can Lift:","[round((strength+endurance*4)*0.45359237)*0.01] kg ([round(strength+endurance*4)*0.01] lbs)")
	//	stat("Energy Signature","[Signature]")
		stat("<hr>----------------------------------</hr>")
		if(race!="Namekian")
			stat("Hunger:","[round(hunger)]%")
		stat("Thirst:","[round(thirst)]%")
		stat("Tiredness:","[round(restedness)]%")
