mob/verb
	Battle_Music_Mute()
		set hidden = 1
		src<<sound(null)
		return 1
mob/verb
	Battle_Music()
		set hidden = 1
		set category="Options"
		switch(input("Which battle song would you like to play?") in list ("Bulma and the Frog","Deep Wild","Dragon Crisis","Earth Music","Frieza Begs","Future Trunks","Gokus Nightmare","Grand Kai Blues","Groovy Disco-Tech","Hell Theme","Kame Sad","King Kai","Lonesome Wild","Lost Courage","Old Kais Dance","Perfect Cell","Power Music","Room Music","Snake Way","Space Room","The Saga Continues"))
			if("Perfect Cell")
				src<<sound(null)
				src<<sound('Perfect Cell.ogg', 1, volume=35)
			if("Deep Wild")
				src<<sound(null)
				src<<sound('Deep Wild.ogg',1,volume=35)
			if("Lonesome Wild")
				src<<sound(null)
				src<<sound('Lonesome Wild.ogg',1,volume=35)
			if("Dragon Crisis")
				src<<sound(null)
				src<<sound('Dragon Crisis.ogg',1,volume=35)
			if("Lost Courage")
				src<<sound(null)
				src<<sound('Lost Courage.ogg',1,volume=35)
			if("Bulma and the Frog")
				src<<sound(null)
				src<<sound('BulmaAndTheFrog.ogg',1,volume=35)
			if("Earth Music")
				src<<sound(null)
				src<<sound('EarthMusic.ogg',1,volume=35)
			if("Frieza Begs")
				src<<sound(null)
				src<<sound('FriezaBegs.ogg',1,volume=35)
			if("Future Trunks")
				src<<sound(null)
				src<<sound('FutureTrunks.ogg',1,volume=35)
			if("Gokus Nightmare")
				src<<sound(null)
				src<<sound('GokusNightmare.ogg',1,volume=35)
			if("Grand Kai Blues")
				src<<sound(null)
				src<<sound('GrandKaiBlues.ogg',1,volume=35)
			if("Groovy Disco-Tech")
				src<<sound(null)
				src<<sound('GroovyDiscotech.ogg',1,volume=35)
			if("Hell Theme")
				src<<sound(null)
				src<<sound('HellTheme.ogg',1,volume=35)
			if("Kame Sad")
				src<<sound(null)
				src<<sound('KameSad.ogg',1,volume=35)
			if("King Kai")
				src<<sound(null)
				src<<sound('KingKai.ogg',1,volume=35)
			if("Old Kais Dance")
				src<<sound(null)
				src<<sound('OldKaisDance.ogg',1,volume=35)
			if("Power Music")
				src<<sound(null)
				src<<sound('PowerMusic.ogg',1,volume=35)
			if("Room Music")
				src<<sound(null)
				src<<sound('RoomMusic.ogg',1,volume=35)
			if("Snake Way")
				src<<sound(null)
				src<<sound('SnakeWay.ogg',1,volume=35)
			if("Space Room")
				src<<sound(null)
				src<<sound('SpaceRoom.ogg',1,volume=35)
			if("The Saga Continues")
				src<<sound(null)
				src<<sound('TheSagaContinues.ogg',1,volume=35)
mob/proc
	VegetaSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('TheSagaContinues.ogg',volume=35)
			if(2)
				src<<sound('GokusNightmare.ogg',volume=35)
			if(3)
				src<<sound('FriezaBegs.ogg',volume=35)
			if(4)
				src<<sound('PowerMusic.ogg',volume=35)


	EarthSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('EarthMusic.ogg',volume=35)
			if(2)
				src<<sound('GokusNightmare.ogg',volume=35)
			if(3)
				src<<sound('GroovyDiscotech.ogg',volume=35)
			if(4)
				src<<sound('PowerMusic.ogg',volume=35)

	NamekSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('BulmaAndTheFrog.ogg',volume=35)
			if(2)
				src<<sound('KameSad.ogg',volume=35)
			if(3)
				src<<sound('DBStheme.ogg',volume=35)
			if(4)
				src<<sound('OldKaisDance.ogg',volume=35)



	IcerSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('FriezaBegs.ogg',volume=35)
			if(2)
				src<<sound('FutureTrunks.ogg',volume=35)
			if(3)
				src<<sound('PowerMusic.ogg',volume=35)
			if(4)
				src<<sound('HellTheme.ogg',volume=35)

	CPSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('RoomMusic.ogg',volume=35)
			if(2)
				src<<sound('KingKai.ogg',volume=35)
			if(3)
				src<<sound('SnakeWay.ogg',volume=35)
			if(4)
				src<<sound('SnakeWay.ogg',volume=35)

	HeavenSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('KingKai.ogg',volume=35)
			if(2)
				src<<sound('RoomMusic.ogg',volume=35)
			if(3)
				src<<sound('KameSad.ogg',volume=35)
			if(4)
				src<<sound('KameSad.ogg',volume=42)

	HellSounds()
		switch(rand(1,5))
			if(1)
				src<<sound('FriezaBegs.ogg',volume=35)
			if(2)
				src<<sound('HellTheme.ogg',volume=35)
			if(3)
				src<<sound('PowerMusic.ogg',volume=35)
			if(4)
				src<<sound('HellTheme.ogg',volume=35)
			if(5)
				src<<sound('GokusNightmare.ogg',volume=35)


	MiscSounds()
		switch(rand(1,4))
			if(1)
				src<<sound('RoomMusic.ogg',volume=35)
			if(2)
				src<<sound('EarthMusic.ogg',volume=35)
			if(3)
				src<<sound('SpaceRoom.ogg',volume=35)
			if(4)
				src<<sound('PowerMusic.ogg',volume=35)


